---
title: "Projects"
pagetitle: "Projects"
title-prefix: "Peter Amerkhanian"
title-block-banner: true
format:
  html:
    toc: false
    toc-depth: 3
---  


## Public Reports, Dashboards, & Software

The following are some of my formal, public-facing projects:

<i class="bi bi-file-bar-graph"></i> **Interactive CalWORKs Resource Model**  
Stephanie Peng, Peter Amerkhanian, Joaquín Carbonell (2024)  
Dashboard for The California Department of Social Services.  
[Live Report](https://www.cdss.ca.gov/inforesources/calworks-summary/program-services-utilization/poverty-measures){.btn .btn-outline-primary .btn-sm role="button"}
[Dashboard](https://public.tableau.com/app/profile/peter.amerkhanian7533/viz/CalWORKsResourceModel/CalWORKsResourceModel){.btn .btn-outline-primary .btn-sm role="button"}
[Static Report](https://drive.google.com/file/d/1xOP5gBiWarYX0LPAnV_fZAT6McTSUm9M/view?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"}  

**Summary**: We produce an interactive tool to model the anti-poverty effects of state/federal supports on families participating in CalWORKs.   
*Contribution*: Co-wrote R code-base, developed Tableau visual.  
Tools: `ipumsr`, Tableau.

---

<i class="bi bi-newspaper"></i> **A Tale of Two Cities: Alameda and Alameda Point**  
Peter Amerkhanian (2023)  
Consultant Report for The City of Alameda Department of Finance.  
[Report](https://drive.google.com/file/d/1V5enQS_yZMJauFjUiydXCRnBW_kn0Wqu/view?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"}
[Executive Summary](https://drive.google.com/file/d/1ZPgBJAXno9L-nKyH6PO5Xrprh5ngch-d/view?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"}   


**Summary**: I utilize various demographic and financial data to analyze redevelopment alternatives in the Alameda Point region.  
Tools: `geopandas`, `sklearn`.

---

<i class="bi bi-newspaper"></i> **A Reexamination of Proposition 13 Using Parcel Level Data**  
Peter Amerkhanian, Max Zhang, and James Hawkins (2023)  
Report for The UC Berkeley Institute for Young Americans.  
[Report](https://youngamericans.berkeley.edu/wp-content/uploads/2023/02/Report_A-Reexamination-of-Proposition-13-Using-Parcel-Level-Data_final.pdf){.btn .btn-outline-primary .btn-sm role="button"}
[Executive Summary](https://youngamericans.berkeley.edu/2023/02/a-reexamination-of-proposition-13-using-parcel-level-data/){.btn .btn-outline-primary .btn-sm role="button"}
[Data Appendix](https://youngamericans.berkeley.edu/wp-content/uploads/2023/02/Report_Benchmarking-The-Zillow-Transaction-and-Assessment-Dataset-ZTRAX_final.pdf){.btn .btn-outline-primary .btn-sm role="button"}

**Summary**: We utilize 12 million property records in California to estimate the tax discount effects of Proposition 13 across property types.   
*Contribution*: Co-wrote R code-base, co-developed statistical design, wrote report draft.  
Tools: `tidyverse`, `marginaleffects`.

---

<i class="bi bi-newspaper"></i> **Supporting Whole Families: SparkPoint® Community Schools**  
Peter Amerkhanian and Ena Yasuhara Li (2021)  
Report for <a href="https://uwba.org/our-impact/research-and-publications/">United Way Bay Area</a>.  
[Report](https://uwba.org/wp-content/uploads/2022/04/21-Support_Whole_families_SparkPoint_Community_Schools.pdf){.btn .btn-outline-primary .btn-sm role="button"} 

**Summary**: I utilize client outcome data and interviews with clients and program staff to evaluate United Way Bay Area's Community Schools program.  
Tools: `pandas`.

---

<i class="bi bi-code-square"></i> **Grade Migration Manager**  
Peter Amerkhanian (2019)  
Software developed for Colegio Ismael Perez Pazmiño via The U.S. Peace Corps.   
[Code](https://github.com/peter-amerkhanian/grade-manager){.btn .btn-outline-primary .btn-sm role="button"} 
[Slides](https://docs.google.com/presentation/d/1c3OQMwLTboWrP0cyoQrkerRkpXzk0QYFBTg6Bycah7c/edit?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"} 
[Demo Video](https://youtu.be/C7hel3R0OKo?si=Oan6iWskowB4NTIB){.btn .btn-outline-primary .btn-sm role="button"}       

**Summary**: I developed a full stack software application to migrate student grade data from a school's excel-based system into the education ministry's java application.  
Tools: `pyautogui`, `xlwings`.


## Teaching

The following are courses and workshops that I've taught, largely at UC Berkeley:

<i class="bi bi-mortarboard"></i> **Python Data Wrangling Workshop**  
Peter Amerkhanian, Pratik Sachdeva, Tom van Nuenen, Aniket Kesari (2023)  
Workshop designed and taught for the UC Berkeley D-Lab.  
[Code](https://github.com/dlab-berkeley/Python-Data-Wrangling/tree/dda0513ab19cf802d82ee76b793038a958d8fc15){.btn .btn-outline-primary .btn-sm role="button"}

**Summary**: I led a re-design of this 3-hour, flagship Python workshop for the UC Berkeley D-Lab. It provides an introduction to basic data wrangling actions -- index, merge, group, and plot -- using `pandas`.  
---

<i class="bi bi-mortarboard"></i> **Python for MBAs**  
Peter Amerkhanian (2023)  
Workshop designed and taught for the UC Berkeley D-Lab.  
[Code](https://github.com/dlab-berkeley/HAAS-Python-Workshop/tree/72a719d13a974806d57a5278748f1083159ebf2e){.btn .btn-outline-primary .btn-sm role="button"}

**Summary**: I designed this one and a half hour workshop and taught it to MBA students at UC Berkeley's Haas Business School. The course directly connects `pandas` functions to equivalent workflows an intermediate Excel user would be familiar with.



## Academic Course Papers
The following are some of my course papers from graduate school:

**Simulating School Desegregation in San Francisco**  
Peter Amerkhanian (2022), <a href="https://www.globalpolicy.science/courses">Public Policy 275</a> Final Paper.  
[Paper](https://drive.google.com/file/d/1vRbN9dOT8-uFneSbTShG2RMmztQULrX4/view?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"}
[Repo](https://github.com/peter-amerkhanian/sf-schools-simulation){.btn .btn-outline-primary .btn-sm role="button"}

**Summary**: I use a synthetic dataset of San Francisco public high school students and spatial optimization methods to simulate the effects of various busing strategies for racial desegregation outcomes.  
Tools: `geopandas`, `networkx`. Methods: dijkstra's algorithm, entropy/dissimilarity statistics.

---

**Measuring Differences in California Politician Agendas in Press Releases**  
Peter Amerkhanian (2021), <a href="https://people.ischool.berkeley.edu/~dbamman/info256.html">Information 254</a> Final Paper.  
[Paper](https://drive.google.com/file/d/134YMeVodA3_kytoq-u8rqO34b3U6Bkoy/view?usp=sharing){.btn .btn-outline-primary .btn-sm role="button"}

**Summary**: I use a novel dataset of press releases issued by governors and mayors in California to 1.) Develop a regression model to identify press release authorship, 2.) Cluster press releases by topic, and 3.) Estimate the political similarities between mayors and governors.  
Tools: `gensim`, `sklearn`. Methods: logistic regression, latent dirichlet allocation.

---


